project_id   = "my-dev-project"
region       = "us-central1"
zone         = "us-central1-a"
machine_type = "e2-small"
disk_image   = "projects/debian-cloud/global/images/family/debian-11"
network      = "default"
