project_id   = "my-prod-project"
region       = "us-central1"
zone         = "us-central1-c"
machine_type = "e2-standard-2"
disk_image   = "projects/debian-cloud/global/images/family/debian-11"
network      = "default"
